export const FETCH_QUERY_KEY = {
  PRODUCT_LOT: "PRODUCT_LOT",
  INVENTORY_BY_LOT: "INVENTORY_BY_LOT",
  PRODUCT_WITH_INVENTORY: "PRODUCT_WITH_INVENTORY",
  B2B_WAREHOUSE_PRODUCTS: "B2B_WAREHOUSE_PRODUCTS",
  B2B_WAREHOUSE_PRODUCT_BY_BARCODE: "B2B_WAREHOUSE_PRODUCT_BY_BARCODE",
  TRANSFER: "TRANSFER",
  // Promotion
  PROMOTIONS: "PROMOTIONS",
  PROMOTION: "PROMOTION",
  VOUCHERS: "VOUCHERS",
  VOUCHERS_WITH_PROMOTION: "VOUCHERS_WITH_PROMOTION",
  ACTIVE_PROMOTIONS: "ACTIVE_PROMOTIONS",
  PROMO_CODES: "PROMO_CODES",
  PROMOTION_FILTER_OPTIONS: "PROMOTION_FILTER_OPTIONS",
  // VAT Invoice
  VAT_INVOICES_IN: "VAT_INVOICES_IN",
  VAT_INVOICE_IN: "VAT_INVOICE_IN",
  VAT_INVOICES_OUT: "VAT_INVOICES_OUT",
  VAT_INVOICE_OUT: "VAT_INVOICE_OUT",
  VAT_INVENTORY_SUMMARY: "VAT_INVENTORY_SUMMARY",
  // Employee Management
  EMPLOYEES: "EMPLOYEES",
  EMPLOYEE: "EMPLOYEE",
  // Patient Management
  PATIENTS: "PATIENTS",
  PATIENT: "PATIENT",
  // User Management
  USERS: "USERS",
  USER: "USER",
};

export const FETCH_SUBMIT_QUERY_KEY = {
  UPDATE_PRODUCT: "UDPATE_PRODUCT",
  UPDATE_INVENTORY_BY_LOT: "UPDATE_INVENTORY_BY_LOT",
  DELETE_PRODUCT_LOT: "DELETE_PRODUCT_LOT",
  CREATE_B2B_QUOTE: "CREATE_B2B_QUOTE",
  ADD_QUOTE_ITEM: "ADD_QUOTE_ITEM",
  // Promotion
  CREATE_PROMOTION: "CREATE_PROMOTION",
  UPDATE_PROMOTION: "UPDATE_PROMOTION",
  DELETE_PROMOTION: "DELETE_PROMOTION",
  CREATE_VOUCHER: "CREATE_VOUCHER",
  UPDATE_VOUCHER: "UPDATE_VOUCHER",
  DELETE_VOUCHER: "DELETE_VOUCHER",
  // VAT Invoice
  CREATE_VAT_INVOICE_IN: "CREATE_VAT_INVOICE_IN",
  UPDATE_VAT_INVOICE_IN: "UPDATE_VAT_INVOICE_IN",
  DELETE_VAT_INVOICE_IN: "DELETE_VAT_INVOICE_IN",
  CREATE_VAT_INVOICE_OUT: "CREATE_VAT_INVOICE_OUT",
  UPDATE_VAT_INVOICE_OUT: "UPDATE_VAT_INVOICE_OUT",
  DELETE_VAT_INVOICE_OUT: "DELETE_VAT_INVOICE_OUT",
  ISSUE_VAT_INVOICE: "ISSUE_VAT_INVOICE",
  CANCEL_VAT_INVOICE_OUT: "CANCEL_VAT_INVOICE_OUT",
  // Employee Management
  CREATE_EMPLOYEE: "CREATE_EMPLOYEE",
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
  // Patient Management
  CREATE_PATIENT: "CREATE_PATIENT",
  UPDATE_PATIENT: "UPDATE_PATIENT",
  DELETE_PATIENT: "DELETE_PATIENT",
  // User Management
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
};
