export const FETCH_QUERY_KEY = {
  PRODUCT_LOT: "PRODUCT_LOT",
  INVENTORY_BY_LOT: "INVENTORY_BY_LOT",
  PRODUCT_WITH_INVENTORY: "PRODUCT_WITH_INVENTORY",
};

export const FETCH_SUBMIT_QUERY_KEY = {
    UPDATE_PRODUCT: "UDPATE_PRODUCT"
}