export const FETCH_QUERY_KEY = {
  PRODUCT_LOT: "PRODUCT_LOT",
  INVENTORY_BY_LOT: "INVENTORY_BY_LOT",
  PRODUCT_WITH_INVENTORY: "PRODUCT_WITH_INVENTORY",
  B2B_WAREHOUSE_PRODUCTS: "B2B_WAREHOUSE_PRODUCTS",
  B2B_WAREHOUSE_PRODUCT_BY_BARCODE: "B2B_WAREHOUSE_PRODUCT_BY_BARCODE",
};

export const FETCH_SUBMIT_QUERY_KEY = {
  UPDATE_PRODUCT: "UDPATE_PRODUCT",
  UPDATE_INVENTORY_BY_LOT: "UPDATE_INVENTORY_BY_LOT",
  DELETE_PRODUCT_LOT: "DELETE_PRODUCT_LOT",
  CREATE_B2B_QUOTE: "CREATE_B2B_QUOTE",
  ADD_QUOTE_ITEM: "ADD_QUOTE_ITEM",
};
